### ISSUE TITLE
Industry funding errors don't mention town/city rules

### ISSUE THREAD

**Issue by nobody6744** [2TallTyler/industries_of_the_caribbean#5]
I cannot construct a sugarcane farm when the option for funding primary industries is on. It tells me that it must be at elevation 1 and not in the desert no matter where i put it, even if both of these are satisfied

**Comment by 2TallTyler** [comment]
Are you trying to fund it near a city? That also causes it to fail -- it needs to have a non-city town as its parent town. (Yes, the error needs to be reworded to say this...)

**Comment by 2TallTyler** [comment]
I'm finally getting around to updating this NewGRF. Sorry for the delay.

The reason it failed was due to proximity to other industries. Going forward, I am removing placement restrictions entirely when funding primary industries. (They'll still be followed when prospecting or generating industries, of course.)
